--Valid Group listings

--Alkali Metals: 1
--Alkaline Earth Metals: 2
--Transition Metals: 3
--Poor Metals: 4
--Other Non-Metals: 5
--Halogens: 6
--Noble Gases: 7
--Actinide: 8
--Lanthanide: 9


--Alkali Metals
INSERT INTO groups VALUES(1,
	 "Alkali Metals", "The alkali metals are a group (column) in the periodic table consisting of the chemical elements lithium (Li), sodium (Na), potassium (K), rubidium (Rb), caesium (Cs), and francium (Fr). This group lies in the s-block of the periodic table as all alkali metals have their outermost electron in an s-orbital: this electron configuration results in their characteristic properties. The alkali metals provide the best example of group trends in properties in the periodic table, with elements exhibiting well-characterized homologous behaviour.",
	 "The alkali metals have very similar properties: they are all shiny, soft, highly reactive metals at standard temperature and pressure and readily lose their outermost electron to form cations with charge +1. They can all be cut easily with a knife due to their softness, exposing a shiny surface that tarnishes rapidly in air due to oxidation by atmospheric moisture and oxygen. Because of their high reactivity, they must be stored under oil to prevent reaction with air, and are found naturally only in salts and never as the free element. In the modern IUPAC nomenclature, the alkali metals comprise the group 1 elements, excluding hydrogen (H), which is nominally a group 1 element but not normally considered to be an alkali metal as it rarely exhibits behaviour comparable to that of the alkali metals. All the alkali metals react with water, with the heavier alkali metals reacting more vigorously than the lighter ones.",
	 "Most alkali metals have many different applications. Two of the most well-known applications of the pure elements are rubidium and caesium atomic clocks, of which caesium atomic clocks are the most accurate and precise representation of time. A common application of the compounds of sodium is the sodium-vapour lamp, which emits very efficient light. Table salt, or sodium chloride, has been used since antiquity. Sodium and potassium are also essential elements, having major biological roles as electrolytes, and although the other alkali metals are not essential, they also have various effects on the body, both beneficial and harmful.");

--Alkaline Earth Metals
INSERT INTO groups Values(2,"Alkaline Earth Metals"
	,"The alkaline earth metals are a group of chemical elements in the periodic table with very similar properties. They are all shiny, silvery-white, somewhat reactive metals at standard temperature and pressure and readily lose their two outermost electrons to form cations with charge 2+ and an oxidation state, or oxidation number of +2. In the modern IUPAC nomenclature, the alkaline earth metals comprise the group 2 elements.",
		"The alkaline earth metals are all silver-colored and soft, and have relatively low densities, melting points, and boiling points. In chemical terms, all of the alkaline metals react with the halogens to form the alkaline earth metal halides, all of which being ionic crystalline compounds (except for beryllium chloride, which is covalent). All the alkaline earth metals except beryllium also react with water to form strongly alkaline hydroxides and, thus, should be handled with great care. The heavier alkaline earth metals react more vigorously than the lighter ones. The alkaline metals have the second-lowest first ionization energies in their respective periods of the periodic table because of their somewhat low effective nuclear charges and the ability to attain a full outer shell configuration by losing just two electrons. The second ionization energy of all of the alkaline metals is also somewhat low.",
			"Beryllium is used mostly for military applications, but there are other uses of beryllium, as well. In electronics, beryllium is used as a p-type dopant in some semiconductors, and beryllium oxide is used as a high-strength electrical insulator and heat conductor. Due to its light weight and other properties, beryllium is also used in mechanics when stiffness, light weight, and dimensional stability are required at wide temperature ranges.
			
			Magnesium has many different uses. One of its most common uses was in industry, where it has many structural advantages over other materials such as aluminium, although this usage has fallen out of favor recently due to magnesium's flammability. Magnesium is also often alloyed with aluminium or zinc to form materials with more desirable properties than any pure metal. Magnesium has many other uses in industrial applications, such as having a role in the production of iron and steel, and the production of titanium.
			
			Calcium also has many uses. One of its uses is as a reducing agent in the separation of other metals from ore, such as uranium. It is also used in the production of the alloys of many metals, such as aluminium and copper alloys, and is also used to deoxidize alloys as well. Calcium also has a role in the making of cheese, mortars, and cement.

			Strontium and barium do not have as many applications as the lighter alkaline earth metals, but still have uses. Strontium carbonate is often used in the manufacturing of red fireworks, and pure strontium is used in the study of neurotransmitter release in neurons. Barium has some use in vacuum tubes to remove gases, and barium sulfate has many uses in the petroleum industry, as well as other industries.

			Due to its radioactivity, radium no longer has many applications, but it used to have many. Radium used to be used often in luminous paints, although this use was stopped after workers got sick. As people used to think that radioactivity was a good thing, radium used to be added to drinking water, toothpaste, and many other products, although they are also not used anymore due to their health effects. Radium is no longer even used for its radioactive properties, as there are more powerful and safer emitters than radium.")

--Transistion Metals
INSERT INTO groups Values(3,"Transition Metals",
	"In chemistry, the term transition metal (or transition element) has two possible meanings:

	The IUPAC definition defines a transition metal as 'an element whose atom has a partially filled d sub-shell, or which can give rise to cations with an incomplete d sub-shell'.
	Most scientists describe a 'transition metal' as any element in the d-block of the periodic table, which includes groups 3 to 12 on the periodic table. In actual practice, the f-block lanthanide and actinide series are also considered transition metals and are called 'inner transition metals'.
	Jensen reviews the history of the terms 'transition element' (or 'metal') and 'd-block'. The word transition was first used to describe the elements now known as the d-block by the English chemist Charles Bury in 1921, who referred to a transition series of elements during the change of an inner layer of electrons (for example n=3 in the 4th row of the periodic table) from a stable group of 8 to one of 18, or from 18 to 32.",
		"There are a number of properties shared by the transition elements that are not found in other elements, which results from the partially filled d shell. These include

		the formation of compounds whose colour is due to d–d electronic transitions
		the formation of compounds in many oxidation states, due to the relatively low reactivity of unpaired d electrons.
		the formation of many paramagnetic compounds due to the presence of unpaired d electrons. A few compounds of main group elements are also paramagnetic (e.g. nitric oxide, oxygen)",
			"Numerous and varied ranging from heavy industry to decorational, the transition metals as a whole exhibit the widest array of uses due to their unique chemical properties.")

--Poor Metals
INSERT INTO groups Values(4,"Poor Metals",
		"In chemistry, post-transition metals are the metallic elements in the periodic table located between the transition metals (to their left) and the metalloids (to their right). Usually included in this category are gallium, indium and thallium; tin and lead; and bismuth. Which elements are counted as post-transition metals depends, in periodic table terms, on where the transition metals are taken to end and where the metalloids or non-metals are taken to start.

	Physically, post-transition metals are soft (or brittle), have poor mechanical strength, and melting points lower than those of the transition metals; most also have boiling points lower than those of the transition metals. Being close to the metal-nonmetal border, their crystalline structures tend to show covalent or directional bonding effects, having generally greater complexity or fewer nearest neighbours than other metallic elements.

	Chemically, they are characterised—to varying degrees—by covalent bonding tendencies, acid-base amphoterism and the formation of anionic species such as aluminates, stannates, and bismuthates (in the case of aluminium, tin, and bismuth, respectively). They can also form Zintl phases (half-metallic compounds formed between highly electropositive metals and moderately electronegative metals or metalloids).

	The expression 'post-transition metals' is used here as there is no IUPAC-approved collective name for these metals. Occasionally, some or all of them have instead been referred to as B-subgroup metals, other metals, or p-block metals; and by at least ten other alternative labels. All these labels are surveyed later in this article.",
		"The poor metals (post-transition metals) are some metallic elements of the p-block of the periodic table that are more electronegative than the transition metals. Their melting and boiling points are generally lower than those of the transition metals, and they are also softer.",
			"Like the transition metals, the usages of poor metals varies greatly from element to element, as few share a completely common set of characteristics.  They do, however, feature prominently in the computational sector for use in batteries, electrodes, and microchips")

--Other Non-Metals
INSERT INTO groups Values(5,"Non-Metals","In chemistry, a nonmetal (or non-metal) is a chemical element that mostly lacks metallic attributes. Physically, nonmetals tend to be highly volatile (easily vaporised), have low elasticity, and are good insulators of heat and electricity; chemically, they tend to have high ionization energy and electronegativity values, and gain or share electrons when they react with other elements or compounds. Seventeen elements are generally classified as nonmetals; most are gases (hydrogen, helium, nitrogen, oxygen, fluorine, neon, chlorine, argon, krypton, xenon and radon); one is a liquid (bromine); and a few are solids (carbon, phosphorus, sulfur, selenium, and iodine).

Moving rightward across the standard form of periodic table, nonmetals adopt structures that have progressively fewer nearest neighbours. Polyatomic nonmetals have structures with either three nearest neighbours, as is the case (for example) with carbon (in its standard state of graphite), or two nearest neighbours (for example) in the case of sulfur. Diatomic nonmetals, such as hydrogen, have one nearest neighbour, and the monatomic noble gases, such as helium, have none. This gradual fall in the number of nearest neighbours is associated with a reduction in metallic character and an increase in nonmetallic character. The distinction between the three categories of nonmetals, in terms of receding metallicity is not absolute. Boundary overlaps occur as outlying elements in each category show (or begin to show) less-distinct, hybrid-like or atypical properties.

Although five times more elements are metals than nonmetals, two of the nonmetals—hydrogen and helium—make up over 99 per cent of the observable Universe, and one—oxygen—makes up close to half of the Earth's crust, oceans and atmosphere. Living organisms are also composed almost entirely of nonmetals, and nonmetals form many more compounds than metals.",
		"There is no rigorous definition of a nonmetal. They show more variability in their properties than do metals. The following are some of the chief characteristics of nonmetals. Physically, they largely exist as monatomic gases, with a few having more substantial (but still open-packed) diatomic or polyatomic forms, unlike metals which are nearly all solid and close-packed; if solid, they generally have a submetallic or dull appearance and are brittle, as opposed to metals, which are lustrous, ductile or malleable; they usually have lower densities than metals; are poor conductors of heat and electricity when compared to metals; and have significantly lower melting points and boiling points than those of metals (with the exception of carbon). Chemically, the nonmetals have relatively high ionisation energy and high electronegativity; they usually exist as anions or oxyanions in aqueous solution; generally form ionic or interstitial compounds when mixed with metals, unlike metals which form alloys; and have acidic oxides whereas the common oxides of the metals are basic.",
				"Non-Metals are the collective make-up of biological life forms.")

--Halogens
INSERT INTO groups Values(6,"Halogens",
	"The halogens or halogen elements (/ˈhælɵdʒɨn/) are a group in the periodic table consisting of five chemically related elements: fluorine (F), chlorine (Cl), bromine (Br), iodine (I), and astatine (At). The artificially created element 117 (ununseptium) may also be a halogen. In the modern IUPAC nomenclature, this group is known as group 17.

	The group of halogens is the only periodic table group that contains elements in three of the four main states of matter at standard temperature and pressure. All of the halogens form acids when bonded to hydrogen. Most halogens are typically produced from minerals or salts. The middle halogens, that is chlorine, bromine and iodine, are often used as disinfectants. Organobromides are the most important class of flame retardants. Elemental halogens are generally toxic.",
			"Halogens are highly reactive, and as such can be harmful or lethal to biological organisms in sufficient quantities. This high reactivity is due to the high electronegativity of the atoms due to their high effective nuclear charge. Because the halogens have seven valence electrons in their outermost energy level, they can gain an electron by reacting with atoms of other elements to satisfy the octet rule. Fluorine is one of the most reactive elements, attacking otherwise-inert materials such as glass, and forming compounds with the usually inert noble gases. It is a corrosive and highly toxic gas. The reactivity of fluorine is such that, if used or stored in laboratory glassware, it can react with glass in the presence of small amounts of water to form silicon tetrafluoride (SiF4). Thus, fluorine must be handled with substances such as Teflon (which is itself an organofluorine compound), extremely dry glass, or metals such as copper or steel, which form a protective layer of fluoride on their surface.

		The high reactivity of fluorine means that, once it does react with something, it bonds with it so strongly that the resulting molecule is very inert and non-reactive to anything else. For example, Teflon is fluorine bonded with carbon.",
				"Both chlorine and bromine are used as disinfectants for drinking water, swimming pools, fresh wounds, spas, dishes, and surfaces. They kill bacteria and other potentially harmful microorganisms through a process known as sterilization. Their reactivity is also put to use in bleaching. Sodium hypochlorite, which is produced from chlorine, is the active ingredient of most fabric bleaches, and chlorine-derived bleaches are used in the production of some paper products. Chlorine also reacts with sodium to create sodium chloride, which is another name for table salt.

		Halogen lamps are a type of incandescent lamp using a tungsten filament in bulbs that are filled with small amounts of iodine and bromine gas. This enables the production of lamps that are much smaller than non-halogen incandescent lightbulbs at the same wattage. The gas reduces the thinning of the filament and blackening of the inside of the bulb resulting in a bulb that has a much greater life. Halogen lamps burn at a higher temperature (2800 to 3400 Kelvin) with a whiter color than incandescent bulbs. However, this requires bulbs to be manufactured from fused quartz rather than silica glass to reduce breakage.

		In drug discovery, the incorporation of halogen atoms into a lead drug candidate results in analogues that are usually more lipophilic and less water-soluble. As a consequence, halogen atoms are used to improve penetration through lipid membranes and tissues. It follows that there is a tendency for some halogenated drugs to accumulate in adipose tissue.

		The chemical reactivity of halogen atoms depends on both their point of attachment to the lead and the nature of the halogen. Aromatic halogen groups are far less reactive than aliphatic halogen groups, which can exhibit considerable chemical reactivity. For aliphatic carbon-halogen bonds, the C-F bond is the strongest and usually less chemically reactive than aliphatic C-H bonds. The other aliphatic-halogen bonds are weaker, their reactivity increasing down the periodic table. They are usually more chemically reactive than aliphatic C-H bonds. As a consequence, the most common halogen substitutions are the less reactive aromatic fluorine and chlorine groups.")

--Noble Gases
INSERT INTO groups Values(7, "Noble Gases", "The noble gases make a group of chemical elements with similar properties: under standard conditions, they are all odorless, colorless, monatomic gases with very low chemical reactivity. The six noble gases that occur naturally are helium (He), neon (Ne), argon (Ar), krypton (Kr), xenon (Xe), and the radioactive radon (Rn).",
	 "The properties of the noble gases can be well explained by modern theories of atomic structure: their outer shell of valence electrons is considered to be 'full', giving them little tendency to participate in chemical reactions, and it has been possible to prepare only a few hundred noble gas compounds. The melting and boiling points for a given noble gas are close together, differing by less than 10 °C (18 °F); that is, they are liquids over only a small temperature range.",
	 	"Neon, argon, krypton, and xenon are obtained from air in an air separation unit using the methods of liquefaction of gases and fractional distillation. Helium is sourced from natural gas fields which have high concentrations of helium in the natural gas, using cryogenic gas separation techniques, and radon is usually isolated from the radioactive decay of dissolved radium, thorium, or uranium compounds (since those compounds give off alpha particles), which are equivalent in mass to the nuclei of a helium-4 atom. Noble gases have several important applications in industries such as lighting, welding, and space exploration. A helium-oxygen breathing gas is often used by deep-sea divers at depths of seawater over 55 m (180 ft) to keep the diver from experiencing oxygen toxemia, the lethal effect of high-pressure oxygen, and nitrogen narcosis, the distracting narcotic effect of the nitrogen in air beyond this partial-pressure threshold. After the risks caused by the flammability of hydrogen became apparent, it was replaced with helium in blimps and balloons.")

--Lanthanides
INSERT INTO groups Values(8,"Lanthanides","The lanthanide /ˈlænθənaɪd/ or lanthanoid /ˈlænθənɔɪd/ series of chemical elements comprises the fifteen metallic chemical elements with atomic numbers 57 through 71, from lanthanum through lutetium. These fifteen lanthanide elements, along with the chemically similar elements scandium and yttrium, are often collectively known as the rare earth elements.

The informal chemical symbol Ln is used in general discussions of lanthanide chemistry to refer to any lanthanide. All but one of the lanthanides are f-block elements, corresponding to the filling of the 4f electron shell; lutetium, a d-block element, is also generally considered to be a lanthanide due to its chemical similarities with the other fourteen. All lanthanide elements form trivalent cations, Ln3+, whose chemistry is largely determined by the ionic radius, which decreases steadily from lanthanum to lutetium.

The lanthanide elements are the group of elements with atomic number increasing from 57 (lanthanum) to 71 (lutetium). They are termed as lanthanides because the lighter elements in the series are chemically similar to lanthanum. Strictly speaking, both lanthanum and lutetium have been labeled as group 3 elements, because they both have a single valence electron in the d shell. However, both elements are often included in any general discussion of the chemistry of the lanthanide elements.

In presentations of the periodic table, the lanthanides and the actinides are customarily shown as two additional rows below the main body of the table, with placeholders or else a selected single element of each series (either lanthanum and actinium, or lutetium and lawrencium) shown in a single cell of the main table, between barium and hafnium, and radium and rutherfordium, respectively. This convention is entirely a matter of aesthetics and formatting practicality; a rarely used wide-formatted periodic table inserts the lanthanide and actinide series in their proper places, as parts of the table's sixth and seventh rows (periods).",
		"All the trivalent lanthanide ions, except lanthanum and lutetium, have unpaired f electrons. However, the magnetic moments deviate considerably from the spin-only values because of strong spin-orbit coupling. The maximum number of unpaired electrons is 7, in Gd3+, with a magnetic moment of 7.94 B.M., but the largest magnetic moments, at 10.4–10.7 B.M., are exhibited by Dy3+ and Ho3+. However, in Gd3+ all the electrons have parallel spin and this property is important for the use of gadolinium complexes as contrast reagent in MRI scans.

				Crystal field splitting is rather small for the lanthanide ions and is less important than spin-orbit coupling in regard to energy levels. Transitions of electrons between f orbitals are forbidden by the Laporte rule. Furthermore, because of the 'buried' nature of the f orbitals, coupling with molecular vibrations is weak. Consequently the spectra of lanthanide ions are rather weak and the absorption bands are similarly narrow. Glass containing holmium oxide and holmium oxide solutions (usually in perchloric acid) have sharp optical absorption peaks in the spectral range 200–900 nm and can be used as a wavelength calibration standard for optical spectrophotometers, and are available commercially.

				As f-f transitions are Laporte-forbidden, once an electron has been excited, decay to the ground state will be slow. This makes them suitable for use in lasers as it makes the population inversion easy to achieve. The Nd:YAG laser is one that is widely used. Europium-doped yttrium vanadate was the first red phosphor to enable the development of color television screens. Lanthanide ions have notable luminescent properties due to their unique 4f orbitals. Laporte forbidden f-f transitions can be activated by excitation of a bound 'antenna' ligand. This leads to sharp emission bands throughout the visible, NIR, and IR and relatively long luminescence lifetimes.","")

--Actinides
INSERT INTO groups Values(9,"Actinides","The actinide /ˈæktɨnaɪd/ or actinoid /ˈæktɨnɔɪd/ (IUPAC nomenclature) series encompasses the 15 metallic chemical elements with atomic numbers from 89 to 103, actinium through lawrencium.

		The actinide series derives its name from the first element in the series, actinium. The informal chemical symbol An is used in general discussions of actinide chemistry to refer to any actinide. All but one of the actinides are f-block elements, corresponding to the filling of the 5f electron shell; lawrencium, a d-block element, is also generally considered an actinide. In comparison with the lanthanides, also mostly f-block elements, the actinides show much more variable valence. They all have very large atomic and ionic radii and exhibit an unusually large range of physical properties. While actinium and the late actinides (from americium onwards) behave similarly to the lanthanides, the elements thorium through neptunium are much more similar to transition metals in their chemistry.

		Of the actinides, primordial thorium and uranium occur naturally in substantial quantities and small amounts of persisting natural plutonium have also been identified. The radioactive decay of uranium produces transient amounts of actinium and protactinium, and atoms of neptunium, americium, curium, berkelium and californium are occasionally produced from transmutation reactions in uranium ores. The other actinides are purely synthetic elements. Nuclear weapons tests have released at least six actinides heavier than plutonium into the environment; analysis of debris from a 1952 hydrogen bomb explosion showed the presence of americium, curium, berkelium, californium, einsteinium and fermium.

		All actinides are radioactive and release energy upon radioactive decay; naturally occurring uranium and thorium, and synthetically produced plutonium are the most abundant actinides on Earth. These are used in nuclear reactors and nuclear weapons. Uranium and thorium also have diverse current or historical uses, and americium is used in the ionization chambers of most modern smoke detectors.",
			"Actinides are typical metals. All of them are soft and have a silvery color (but tarnish in air), relatively high density and plasticity. Some of them can be cut with a knife. Their electrical resistivity varies between 15 and 150 µOhm·cm. The hardness of thorium is similar to that of soft steel, so heated pure thorium can be rolled in sheets and pulled into wire. Thorium is nearly half as dense as uranium and plutonium, but is harder than either of them. All actinides are radioactive, paramagnetic, and, with the exception of actinium, have several crystalline phases: plutonium has seven, and uranium, neptunium and californium three. Crystal structures of protactinium, uranium, neptunium and plutonium do not have clear analogs among the lanthanides and are more similar to those of the 3d-transition metals.

			All actinides are pyrophoric, especially when finely divided, that is, they spontaneously ignite upon reaction with air. The melting point of actinides does not have a clear dependence on the number of f-electrons. The unusually low melting point of neptunium and plutonium (~640 °C) is explained by hybridization of 5f and 6d orbitals and the formation of directional bonds in these metals.",
				"While actinides have some established daily-life applications, such as in smoke detectors (americium) and gas mantles (thorium), they are mostly used in nuclear weapons and use as a fuel in nuclear reactors. The last two areas exploit the property of actinides to release enormous energy in nuclear reactions, which under certain conditions may become self-sustaining chain reaction.
					About half of the produced thorium is used as the light-emitting material of gas mantles. Thorium is also added into multicomponent alloys of magnesium and zinc. So the Mg-Th alloys are light and strong, but also have high melting point and ductility and thus are widely used in the aviation industry and in the production of missiles. Thorium also has good electron emission properties, with long lifetime and low potential barrier for the emission. The relative content of thorium and uranium isotopes is widely used to estimate the age of various objects, including stars (see radiometric dating).

The major application of plutonium has been in nuclear weapons, where the isotope plutonium-239 was a key component due to its ease of fission and availability. Plutonium-based designs allow reducing the critical mass to about a third of that for uranium-235. The "Fat Man"-type plutonium bombs produced during the Manhattan Project used explosive compression of plutonium to obtain significantly higher densities than normal, combined with a central neutron source to begin the reaction and increase efficiency. Thus only 6.2 kg of plutonium was needed for an explosive yield equivalent to 20 kilotons of TNT. (See also Nuclear weapon design.) Hypothetically, as little as 4 kg of plutonium—and maybe even less—could be used to make a single atomic bomb using very sophisticated assembly designs.

Plutonium-238 is potentially more efficient isotope for nuclear reactors, since it has smaller critical mass than uranium-235, but it continues to release much thermal energy (0.56 W/g) by decay even when the fission chain reaction is stopped by control rods. Its application is limited by the high price (about 1000 USD/g). This isotope has been used in thermopiles and water distillation systems of some space satellites and stations. So Galileo and Apollo spacecraft (e.g. Apollo 14) had heaters powered by kilogram quantities of plutonium-238 oxide; this heat is also transformed into electricity with thermopiles. The decay of plutonium-238 produces relatively harmless alpha particles and is not accompanied by gamma-irradiation. Therefore this isotope (~160 mg) is used as the energy source in heart pacemakers where it lasts about 5 times longer than conventional batteries.

Actinium-227 is used as a neutron source. Its high specific energy (14.5 W/g) and the possibility of obtaining significant quantities of thermally stable compounds are attractive for use in long-lasting thermoelectric generators for remote use. 228Ac is used as an indicator of radioactivity in chemical research, as it emits high-energy electrons (2.18 MeV) that can be easily detected. 228Ac-228Ra mixtures are widely used as an intense gamma-source in industry and medicine.

Development of self-glowing actinide-doped materials with durable crystalline matrices is a new area of actinide utilization as the addition of alpha-emitting radionuclides to some glasses and crystals may confer luminescence.")

commit();